
# require_relative '../node_modules/react-native-unimodules/cocoapods'
# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")


platform :ios, '12.0'

target 'apployMe' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    #to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  

  # Other native modules
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # react-native-cli autolinking
  use_native_modules!


 # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
  #post_install do |installer|
  #  react_native_post_install(installer)
  #end

end
